### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by rugk** [LeeBrotherston/tls-fingerprinting#31]
Please [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your [releases](https://help.github.com/articles/about-releases/), so they can be seen [on GitHub](https://help.github.com/articles/creating-releases/).

**Comment by LeeBrotherston** [comment]
Ah perfect, thank you.  Was completely unaware that github had features for this...  I'll start doing that!

**Comment by LeeBrotherston** [comment]
I have tagged and set release of version 1.0.0 as all the major bugs are closed.

Thanks so much for the input, it's really valuable.
