### ISSUE TITLE
Does this work with ipv6?

### ISSUE THREAD

**Issue by abdulhannanali** [LeeBrotherston/tls-fingerprinting#41]
Hi,

I just wanted to know if fingerprinTLS code can only fingerprint on ipv4 connection or on ipv6 connections as well. Thanks a lot. have a great day. 

Kind Regards,
Hannan

**Comment by abdulhannanali** [comment]
It does work thanks a lot

**Comment by LeeBrotherston** [comment]
Hah - sorry I didn't reply before you worked it out, but yes IPv6 should work 👍

**Comment by abdulhannanali** [comment]
@LeeBrotherston Thanks for this amazing way to fingerprint clients and detect malicious traffic. I am not a C developer or don't do low level but it still compiled in the first go after i installed libpcap-dev on my ubuntu machine.
